Repository open-sir/open-sir, pull requests merged in 2020-04, with the labels that each got.

#23 tests: add two tests to SIR
  tests/__init__.py
  tests/test_sir.py
Labels: enhancement

#19 docs: intro README
  README.md
Labels: documentation

#54 setup.py: Specify encoding for long description
  setup.py
Labels: bug
